# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNDemo
  
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'

  
  target 'RNDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNDemo-tvOS

  target 'RNDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
